---
title: "Group28_CS971"
author: "celia rubio madrigal, girish koushik"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(quantmod)
library(hydroPSO)
library(ggplot2)
library(gramEvol)
```

```{r}
backtest_signal <- function(trading_signal, prices, initial_capital = 10000) {
    cash_value <- rep(NA, length(trading_signal) + 1)
    asset_value <- rep(NA, length(trading_signal) + 1)
    number_of_shares <- rep(NA, length(trading_signal) + 1)

    trading_signal <- as.vector(trading_signal)
    prices <- as.vector(prices)

    cash_value[1] <- initial_capital
    asset_value[1] <- 0
    number_of_shares[1] <- 0

    for (i in 1:(length(trading_signal))) {
        if (trading_signal[i] == 1 && cash_value[i] >= prices[i]) {
            # buy
            number_of_shares[i + 1] <- number_of_shares[i] + 1
            cash_value[i + 1] <- cash_value[i] - prices[i]
        } else if (trading_signal[i] == -1 && number_of_shares[i] > 0) {
            # sell
            number_of_shares[i + 1] <- number_of_shares[i] - 1
            cash_value[i + 1] <- cash_value[i] + prices[i]
        } else {
            # hold
            number_of_shares[i + 1] <- number_of_shares[i]
            cash_value[i + 1] <- cash_value[i]
        }
        asset_value[i + 1] <- number_of_shares[i + 1] * prices[i]
    }
    return(data.frame(
        cash_value = cash_value, asset_value = asset_value,
        number_of_shares = number_of_shares, total_value = cash_value + asset_value
    ))
}
```


```{r}
get_signal <- function(params, index) {
    fast = as.integer(params[1])
    slow = as.integer(params[2])
    signal = as.integer(params[3])

    macd <- MACD(index, nFast = fast, nSlow = slow, nSig = signal, maType = "EMA")

    trading_signal <- ifelse(macd$macd - macd$signal > 0.1, 1, ifelse(macd$macd - macd$signal < -0.1, -1, 0))
    trading_signal[is.na(trading_signal)] <- 0

    return(trading_signal)
}
```

```{r}
get_profit <- function(trading_signal, index) {
    initial_capital <- 10000
    backtest <- backtest_signal(trading_signal, index, initial_capital)
    profit <- backtest$total_value[length(backtest$total_value)] - backtest$total_value[1]
    return(profit)
}
```

```{r}
fitness_function <- function(params, index) {
    trading_signal <- get_signal(params, index)
    return(-get_profit(trading_signal, index))
}
```

```{r}
get_optimal_parameter <- function(lower_bounds, upper_bounds, index) {
    this_fitness <- function(params) {
        return(fitness_function(params, index))
    }
    opt_results <- hydroPSO(fn = this_fitness, lower = lower_bounds, upper = upper_bounds, control = list(c1 = 2, c2 = 2, maxit = 100))
    optimal_params <- as.integer(opt_results$par)
    return(optimal_params)
}
```

```{r}
get_majority_signal <- function(pool) {
    # sum the pool signals across the 4 columns
    signal_sum <- rowSums(pool)
    new_signal <- ifelse(signal_sum >= 2, 1, ifelse(signal_sum <= -2, -1, 0))
    return(new_signal)
}
```

```{r}
plot_graph <- function(variable, yvalue, legend, title, xlab, ylab) {
    ggplot(variable, aes(x = index(variable))) +
    geom_line(aes(y = yvalue[1], color = as.character(legend[1]))) +
    geom_line(aes(y = yvalue[2], color = as.character(legend[2]))) +
    geom_line(aes(y = yvalue[3], color = as.character(legend[3]))) +
    geom_line(aes(y = yvalue[4], color = as.character(legend[4]))) +
    labs(title = title, x = xlab, y = ylab) +
    theme_minimal()
}
```

```{r}
# Training data: SPY index from 2018 to 2021
getSymbols("SPY", src = "yahoo", from = "2018-01-01", to = "2021-12-31")
training_index <- Cl(SPY)
```

```{r}
set.seed(42)
parameter_small <- get_optimal_parameter(c(1,5,5),c(5,20,50),training_index)
parameter_med <- get_optimal_parameter(c(1,15,5),c(15,50,50),training_index)
parameter_big <- get_optimal_parameter(c(1,50,5),c(50,200,50),training_index)
parameter_common <- c(12, 26, 9)
```

```{r}
signal_small <- get_signal(parameter_small, training_index)
signal_med <- get_signal(parameter_med, training_index)
signal_big <- get_signal(parameter_big, training_index)
signal_common <- get_signal(parameter_common, training_index)
```

```{r}
pool_signals <- data.frame(signal_small, signal_med, signal_big, signal_common)
colnames(pool_signals) <- c("signal_small", "signal_med", "signal_big", "signal_common")
```

```{r}
plot_graph(cumsum(pool_signals), pool_signals, colnames(pool_signals), "Cumulative sum of signals", "Date", "Cumulative sum of signals")
```

```{r}
get_investment_values <- function(parameter, index) {
    signal <- get_signal(parameter, index)
    backtest <- backtest_signal(signal, index, 10000)
    return(backtest$total_value)
}
```

```{r}
pool_values <- data.frame(
  get_investment_values(parameter_small, training_index), get_investment_values(parameter_med, training_index),
  get_investment_values(parameter_big, training_index), get_investment_values(parameter_common, training_index)
)
colnames(pool_values) <- c("value_small", "value_med", "value_big", "value_common")
```

```{r}
plot_graph(pool_values, pool_values, colnames(pool_values), "Investment values", "Date", "Investment value")
```

```{r}
# Expects small, med, big, common
get_grammar_expr <- function(signals) {
  # Define our grammar
  rules <- list(expr = grule(op(expr, expr),var),
              op = grule('+', '-', '*'),
              var = grule(signals$small, signals$med, signals$big, signals$common))

  # Create grammar from rules
  grammar <- CreateGrammar(rules)

  grammar_fitness <- function(expr) {
    signal <- eval(expr)
    return(-get_profit(signal,training_index))
  }

  ge <- GrammaticalEvolution(grammar, grammar_fitness, iterations = 500, max.depth = 5)
  expr <- ge$best$expressions
  return(expr)
}

get_grammar_signal <- function(signals,expr) {
  return(eval(expr))
}

all_signals <- data.frame(small=signal_small, med=signal_med, big=signal_big, common=signal_common)
names(all_signals) <- c('small','med','big','common')
grammar_expr <- get_grammar_expr(all_signals)
grammar_signal <- get_grammar_signal(all_signals,grammar_expr)
```

```{r}
majority_signal <- get_majority_signal(pool_signals)
all_signals <- data.frame(pool_signals, majority_signal)
```

```{r}
plot_graph(cumsum(all_signals), all_signals, colnames(all_signals), "Signals", "Date", "Signal")
```

```{r}
# Test data: SPY index from 2022 to 2023 and QQQ index from 2018 to 2021
getSymbols("SPY", src = "yahoo", from = "2022-01-01", to = "2023-01-01")
test_year <- Cl(SPY)
getSymbols("QQQ", src = "yahoo", from = "2018-01-01", to = "2021-12-31")
test_index <- Cl(QQQ)
```

```{r}
# Evaluate on test data
test_signal_small <- get_signal(parameter_small, test_year)
test_signal_med <- get_signal(parameter_med, test_year)
test_signal_big <- get_signal(parameter_big, test_year)
test_signal_common <- get_signal(parameter_common, test_year)
```

```{r}
pool_signals_test <- data.frame(test_signal_small, test_signal_med, test_signal_big, test_signal_common)
colnames(pool_signals_test) <- c("test_signal_small", "test_signal_med", "test_signal_big", "test_signal_common")
```

```{r}
plot_graph(cumsum(pool_signals_test), pool_signals_test, colnames(pool_signals_test), "Cumulative sum of signals", "Date", "Cumulative sum of signals")
```

```{r}
pool_values_test <- data.frame(
  get_investment_values(parameter_small, test_year), get_investment_values(parameter_med, test_year),
  get_investment_values(parameter_big, test_year), get_investment_values(parameter_common, test_year)
)
colnames(pool_values_test) <- c("value_small_test", "value_med_test", "value_big_test", "value_common_test")
```

```{r}
plot_graph(pool_values_test, pool_values_test, colnames(pool_values_test), "Investment values", "Date", "Investment value")
```

```{r}
majority_signal_test <- get_majority_signal(pool_signals_test)
all_signals_test <- data.frame(pool_signals_test, majority_signal_test)
```

```{r}
plot_graph(cumsum(all_signals_test), all_signals_test, colnames(all_signals_test), "Signals", "Date", "Signal")
```
